version: '3'
volumes:
  app-data: { }
services:
  app:
    build: .
    image: pfhhbq/devops_lab01:latest
    volumes:
      - app-data:/usr/src/app_python
    ports:
      - "5000:5000"
    environment:
      - USER_LOGIN=${USER_LOGIN}
      - USER_PASS=${USER_PASS}
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 50M
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
        tag: "{{.ImageName}}|{{.Name}}"