version: "3"

networks:
  monitoring:

services:
  loki:
    image: grafana/loki:2.3.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - monitoring
    volumes:
      - ./loki-config.yml:/etc/loki/loki-config.yml
      - loki-data:/tmp/loki/
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
        tag: "{{.ImageName}}|{{.Name}}"

  promtail:
    depends_on:
      - loki
    image: grafana/promtail:2.3.0
    volumes:
      - ./promtail.yml:/etc/promtail/promtail.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - promtail-data:/var/lib/promtail/positions
    command: -config.file=/etc/promtail/promtail.yml
    expose:
      - 9080
    ports:
      - "9080:9080"
    networks:
      - monitoring
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
        tag: "{{.ImageName}}|{{.Name}}"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - monitoring
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
        tag: "{{.ImageName}}|{{.Name}}"

volumes:
  grafana-data: {}
  loki-data: {}
  promtail-data: {}