apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-lab-deployment
  labels:
    app: flask
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask
          image: pfhhbq/devops_lab01:latest
          ports:
            - containerPort: 8000
          env:
            - name: USER_LOGIN
              value: "q"
            - name: USER_PASS
              value: "q"
