apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "flask-devops-app.fullname" . }}
  labels:
  {{- include "flask-devops-app.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  serviceName: {{ .Values.serviceName}}
  replicas: {{ .Values.replicaCount }}
  podManagementPolicy: { { .Values.podManagementPolicy } }
  {{- end }}

  selector:
    matchLabels:
  {{- include "flask-devops-app.selectorLabels" . | nindent 6 }}
  volumeClaimTemplates:
    - metadata:
        name: tmp
      spec:
        accessModes: [ "ReadWrite" ]
        resources:
          requests:
            storage: 1Gi
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
    {{- include "flask-devops-app.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "flask-devops-app.serviceAccountName" . }}
      securityContext:
      {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: install
          image: busybox
          command:
            - wget
            - "-O"
            - "/inittest/index.html"
            - http://info.cern.ch
          volumeMounts:
            - name: inittest
              mountPath: "/inittest"
      volumes:
        - name: inittest
          emptyDir: { }
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: inittest
              mountPath: /inittest
          env:
            - name: USER_LOGIN
              valueFrom:
                secretKeyRef:
                  name: app-credentials
                  key: username
            - name: USER_PASS
              valueFrom:
                secretKeyRef:
                  name: app-credentials
                  key: password
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "150m"
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: { { .Values.ProbeUrl } }
              port: http
          readinessProbe:
            httpGet:
              path: {{ .Values.ProbeUrl}}
              port: http
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
  {{- toYaml . | nindent 8 }}
  {{- end }}